version: '3'

services:

  run-app:
      build:
        context: .
        dockerfile: ./docker/runApp/Dockerfile
      command: "yarn dev"
      platform: linux/amd64
      network_mode: "host"
      image: app

  run-tests:
    build:
      context: .
      dockerfile: ./docker/runTests/Dockerfile
    platform: linux/amd64
    network_mode: "host"
    depends_on:
      - run-app
    image: tests
    volumes:
      - ./reports/allure-results/docker:/tests/allure-results

  allure:
    image: frankescobar/allure-docker-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: None
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./reports/allure-results/docker:/app/allure-results
      - ./reports/allure-reports/docker:/app/default-reports