name: Run WDIO Tests and Upload Allure Reports for Cypress Real World App
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: Install yarn
        run: npm install yarn@latest -g

      - name: Clone Website Repository
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-realworld-app
          ref: develop
          path: ./cypress-realworld-app

      - name: Run Server
        working-directory: ./cypress-realworld-app
        run: |
          yarn install
          yarn dev &
          sleep 15

      - name: Install Dependencies
        run: npm install

  test-chrome:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run wdio:run:chrome

      - name: Generate Allure Report
        if: always()
        run: npm run report:generate:chrome

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-chrome
          publish_dir: reports/allure-reports/chrome

  test-firefox:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run wdio:run:firefox

      - name: Generate Allure Report
        if: always()
        run: npm run report:generate:firefox

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-firefox
          publish_dir: reports/allure-reports/firefox
          
  test-edge:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run wdio:run:edge
        
      - name: Generate Allure Report
        if: always()
        run: npm run report:generate:edge
        
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-edge
          publish_dir: reports/allure-reports/edge