name: Run WDIO Tests and Upload Allure Reports for Cypress Real World App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: Install Yarn
        run: npm install yarn@latest -g

      - name: Clone Website Repository
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-realworld-app
          ref: develop
          path: ./cypress-realworld-app

      - name: Run Server
        working-directory: ./cypress-realworld-app
        run: |
          yarn install
          yarn dev &
          sleep 30

  test-chrome:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run wdio:run:chrome
        continue-on-error: true

      - name: Generate Allure Report for Chrome
        if: always()
        run: npm run report:generate:chrome

      - name: Deploy Report to Github Pages for Chrome
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-reports/chrome
          destination_dir: chrome

  test-firefox:
    needs: [setup, test-chrome]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run wdio:run:firefox
        continue-on-error: true

      - name: Generate Allure Report for Firefox
        if: always()
        run: npm run report:generate:firefox

      - name: Deploy Report to Github Pages for Firefox
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-reports/firefox
          destination_dir: firefox

  test-edge:
    needs: [setup, test-chrome, test-firefox]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run wdio:run:edge
        continue-on-error: true

      - name: Generate Allure Report for Edge
        if: always()
        run: npm run report:generate:edge

      - name: Deploy Report to Github Pages for Edge
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-reports/edge
          destination_dir: edge
          
