name: Run WDIO Tests and Upload Allure Reports for Cypress Real World App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        test-job: [chrome, firefox, edge]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: Install Yarn
        run: npm install yarn@latest -g

      - name: Clone Website Repository
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-realworld-app
          ref: develop
          path: ./cypress-realworld-app

      - name: Run Server
        working-directory: ./cypress-realworld-app
        run: |
          yarn install
          yarn dev &
          sleep 15

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run wdio:run:${{ matrix.test-job }}
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        run: npm run report:generate:${{ matrix.test-job }}

      - name: Deploy Report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-reports/${{ matrix.test-job }}
          destination_dir: ${{ matrix.test-job }}
